@Webhooks.Api_HostAddress = https://localhost:7009

GET {{WebHook_HostAddress}}/weatherforecast/
Accept: application/json

###  Create order

POST {{Webhooks.Api_HostAddress}}/orders
Content-Type: application/json
{
  "customerName": "Alex",
  "amount": 123459
}

### Create subscription
POST {{Webhooks.Api_HostAddress}}/webhooks/subscriptions
Content-Type: application/json
{
    "eventType": "order.created",
    "webhookUrl": "https://webhook.site/c594eb8a-fc3e-4b40-ab38-19e277ab10d3"
}